### ISSUE TITLE
Signature file is missing

### ISSUE THREAD

**Issue by nnombela** [wolandmaster/luci-app-rtorrent#1]
* opkg_download: Failed to download https://github.com/wolandmaster/luci-app-rtorrent/releases/download/packages/Packages.sig, wget returned 8.

**Comment by wolandmaster** [comment]
Sorry, I missed your issue. Signature file is a new feature in Chaos Calmer (15.05) and this openwrt release not yet supported by this app. I'll check it and commit a fix.

**Comment by hmvs** [comment]
any progress? thanks

**Comment by wolandmaster** [comment]
The OpenWrt 15.05 (Chaos Calmer) compatible version added to releases. The install instruction (README.md) updated accordingly.
