### ISSUE TITLE
Closed XMLRPC log.

### ISSUE THREAD

**Issue by gendouhydeist** [wolandmaster/luci-app-rtorrent#10]
Hi, I'm unable to open luci rtorrent because of socket nil value.

When I install latest luci-app-rtorrent, i get
Downloading https://github.com/wolandmaster/luci-app-rtorrent/releases/download/latest/luci-app-rtorrent_0.1.4_all.ipk.
Configuring luci-app-rtorrent.
**uci: Parse error (invalid command) at line 1, byte 0**

Now when I open rtorrent I get
(22:40:01) Using 'epoll' based polling.
(22:40:01) Using 'epoll' based polling.
(22:40:01) Using 'epoll' based polling.
**(22:40:01) Closed XMLRPC log.**

Which causes xmlrpc to crash and unable to open luci-app-rtorrent.

BTW I'm using latest trunk OpenWRT Designated Driver, and it's better to change the port of xmlrpc because miniupnpd is also using that port.

**Comment by wolandmaster** [comment]
I'm not yet tried Designated Driver because it is not released, so probably sg. is changed in openwrt or rtorrent.
Thanks for the hint regarding the port, I'll add a configure option to the admin menu.

**Comment by gendouhydeist** [comment]
Actually the 0.1.3 was working a week ago on DD, I'll try 0.1.3 today and let you know.

**Comment by wolandmaster** [comment]
Is 0.1.3 working on DD?

**Comment by gendouhydeist** [comment]
nope :(

**Comment by wolandmaster** [comment]
Maybe something is changed in DD trunk meanwhile

**Comment by gendouhydeist** [comment]
is there anyway to restart scgi server?

**Comment by wolandmaster** [comment]
What do you mean exactly? There is no dedicated scgi server is running, because uhttpd (the built in http server) does not support scgi. All xml-rpc calls are converted to netstring and transferred directly to rtorrent. So basically rtorrent is the scgi server.

You can restart the web server and rtorrent with the following commands:
/etc/init.d/uhttpd restart
/etc/init.d/rtorrent restart  (if you have such script)

**Comment by gendouhydeist** [comment]
retest everything and works fine with the DD.

although when you install luci-app-torrent this show up.

Installing luci-app-rtorrent (0.1.5) to root...
Downloading https://github.com/wolandmaster/luci-app-rtorrent/releases/download/latest/luci-app-rtorrent_0.1.5_all.ipk.
Configuring luci-app-rtorrent.
**uci: Parse error (invalid command) at line 1, byte 0**
