### ISSUE TITLE
Pleas add support build to from all sources - not only this packages individual (CC and DD)

### ISSUE THREAD

**Issue by build000** [wolandmaster/luci-app-rtorrent#11]
...

**Comment by wolandmaster** [comment]
Actually this app is contains only lua scripts, so it should work on DD without any modification, but the new openwrt versions are always introduce some non-backward compatible modification. So I always have to check the new openwrt release and adjust the app to it.

**Comment by gendouhydeist** [comment]
@wolandmaster 
does copying files on respected directories would suffice? I would like to add it on my buildroot.

**Comment by wolandmaster** [comment]
Yes, I guess (I've never tried to build openwrt). You can find the dependencies and install scripts under control folder.
