### ISSUE TITLE
Problem with OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-142-gb6330a1 Release (git-15.363.78009-956be55) 

### ISSUE THREAD

**Issue by itrankolov** [wolandmaster/luci-app-rtorrent#12]
After installing rtorrent-rpc and latest luci-app-rtorrent I get the following errors in the logfiles:

Thu Mar 31 15:22:40 2016 daemon.err uhttpd[1553]: /usr/lib/lua/luci/dispatcher.lua:433: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
Thu Mar 31 15:22:40 2016 daemon.err uhttpd[1553]: The called action terminated with an exception:
Thu Mar 31 15:22:40 2016 daemon.err uhttpd[1553]: /usr/lib/lua/xmlrpc/scgi.lua:24: attempt to index local 'sock' (a nil value)
Thu Mar 31 15:22:40 2016 daemon.err uhttpd[1553]: stack traceback:
Thu Mar 31 15:22:40 2016 daemon.err uhttpd[1553]:       [C]: in function 'assert'
Thu Mar 31 15:22:40 2016 daemon.err uhttpd[1553]:       /usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
Thu Mar 31 15:22:40 2016 daemon.err uhttpd[1553]:       /usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>

**Comment by wolandmaster** [comment]
Duplicate. See #5, #7

**Comment by itrankolov** [comment]
Hi there,

I resolved it, by starting rtorrent from cli and resolving all the error messages that were there via the config file. After that it is working as it should.

**Comment by memo1907fener** [comment]
Hi brother,

i installed and configured everything like in the description on Githubpage but every time im getting following error if i want open torrent section via LuCi interface:

> /usr/lib/lua/luci/dispatcher.lua:433: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
The called action terminated with an exception:
/usr/lib/lua/rtorrent.lua:48: 

> Failedto connect to rtorrent: rpc port not reachable!
Possible reasons:
- not the rpc version of rtorrent is installed
- scgi port is not defined in .rtorrent.rc (scgi_port = 127.0.0.1:5000)
- rtorrent is not running (ps | grep rtorrent)

> stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>


I read that the rpc port must be opened i tried it but now i dont now how can i handle with this issue.

**Comment by gendouhydeist** [comment]
if you have miniupnpd running you have to change the port of your scgi
/usr/lib/lua/rtorrent.lua
.rctorrent

**Comment by memo1907fener** [comment]
Do you know how i can change the port? I mean where is the configuration file to change it?

**Comment by wolandmaster** [comment]
You have to change it in /root/.rtorrent.rc :
scgi_port = 127.0.0.1:5001

and in /usr/lib/lua/rtorrent.lua :
local SCGI_PORT = 5001

I will add a config option for it to the next release.

**Comment by memo1907fener** [comment]
Thank you for quick reply wolandmaster. As desribed i changed the ports in .rtorrent.rc and rtorrrent.lua but same error with rpc.. Do you have any idea?

**Comment by wolandmaster** [comment]
Please send me the output of the steps that descriebed in issue #5
