### ISSUE TITLE
Lua pattern matching for every item

### ISSUE THREAD

**Issue by marnunez** [wolandmaster/luci-app-rtorrent#15]
Hi! Simple question: how do I download all the items in my RSS feed? I tried with .\* with no results. And is there a way to manage feed update intervals?

Thanks for your help

**Comment by wolandmaster** [comment]
The ".*" regex should be OK, could you please send me a sample feed xml.

You can change the rss feed fetch interval by change the schedule time in your .rtorrent.rc file (the default value is 5 minutes):
```
# grep schedule /root/.rtorrent.rc 
schedule = rss_downloader,300,300,"execute=/usr/lib/lua/rss_downloader.lua"
```
https://github.com/rakshasa/rtorrent/wiki/COMMAND-Scheduling

**Comment by wly333** [comment]
Hello, I use ".*" to match everything, with except / mini size / max size blank, but still nothing happen.
And how to get my sample feed xml?

**Comment by wly333** [comment]
Using SSH to attach rtorrent session of screen, i found some info of rss_downloader: "Scheduled command failed: rss_downloader: Bad return code." Do i set something wrong?
By the way, it seems that through luci-app-rtorrent, adding a torrent of nearly 270G size results a wrong message.
