### ISSUE TITLE
problem with OpenWrt Chaos Calmer 15.05.1 / LuCI 15.05-149-g0d8bbd2 Release (git-15.363.78009-956be55)

### ISSUE THREAD

**Issue by sentball** [wolandmaster/luci-app-rtorrent#17]
/usr/lib/lua/luci/dispatcher.lua:433: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
The called action terminated with an exception:
error loading module 'lxp' from file '/usr/lib/lua/lxp.so':
	File not found
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>

**use ruTorrent work fine, but it is so serious on a router, lightly webgui is well**

**Comment by wolandmaster** [comment]
It seems you not installed **luaexpat** package that provides lxp.so. I don't know how it is possible because it defined as dependency for luci-app-rtorrent.

**Comment by sentball** [comment]
I tried reinstall several times. and check that **lxp.so** was existed.

**Comment by wolandmaster** [comment]
Is it working now? (if the /usr/lib/lua/lxp.so file exists then you should not get the above error message)

**Comment by sentball** [comment]
nope...i have no idea with this

**libtorrent - 0.13.6-git-1-14e793b75dac95c51ad64ff9cd2dc6772b68c625
rtorrent-rpc - 0.9.6-git-1-62cb5a4605c0664bc522e0e0da9c72f09cf643a9
luci-app-rtorrent - 0.1.5**

do rebuild new version **libtorrent rtorrent-rpc** would cause this problem? (and it is installed on my usb device).

**Comment by wolandmaster** [comment]
What about luaexpat? Which version installed? Is there any suspicious in **logread** output?
Please send me the output of `ls -la /usr/lib/lua/lxp.so /usr/lib/lua/lxp/lom.lua`

**Comment by sentball** [comment]
**luaexpat - 1.3.0-1**

**-rw-r--r--    1 root     root         14284 Jan 31  2016 /usr/lib/lua/lxp.so
-rw-r--r--    1 root     root          1422 Jan 31  2016 /usr/lib/lua/lxp/lom.lua**

not any other suspicious log

**Comment by gendouhydeist** [comment]
weird though never happened to me.

please make sure that your running all the dependencies below.
`opkg list-installed | grep lua`
```
liblua - 5.1.5-1
lua - 5.1.5-1
luaexpat - 1.3.0-1
luasec - 0.6-1
luasocket - 3.0-rc1-20130909-3
```

**Comment by netomx** [comment]
reboot?

Ernesto Villarreal

**Comment by sentball** [comment]
opkg list-installed | grep lua 
result:

**libiwinfo-lua - 2015-06-01-ade8b1b299cbd5748db1acf80dd3e9f567938371
liblua - 5.1.5-1
libubus-lua - 2015-05-25-f361bfa5fcb2daadf3b160583ce665024f8d108e
libuci-lua - 2015-08-27.1-1
lua - 5.1.5-1
luaexpat - 1.3.0-1
luasec - 0.5.1-1
luasocket - 3.0-rc1-20130909-3**

only different is the luasec - 0.5.1-1. from the source opkg can't found luasec - 0.6-1
