### ISSUE TITLE
help installing

### ISSUE THREAD

**Issue by newdietpi** [wolandmaster/luci-app-rtorrent#19]
I get the following error when trying to access through luci.

I have the rpc package installed, the ip set in the config.

```
`/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
The called action terminated with an exception:
/usr/lib/lua/rtorrent.lua:48: 

Failed to connect to rtorrent: rpc port not reachable!
Possible reasons:
- not the rpc version of rtorrent is installed
- scgi port is not defined in .rtorrent.rc (scgi_port = 127.0.0.1:5000)
- rtorrent is not running (ps | grep rtorrent)

stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:460: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>
````

Here's what I have done.

```
# grep scgi /root/.rtorrent.rc
scgi_port = 127.0.0.1:5000

# ps | grep rtorrent 
6420 root      1112 R    grep rtorrent

# netstat -pantu | grep `5000`
```

I think I have to install netstat since it doesn't return anything?

**Comment by wolandmaster** [comment]
And what about rtorrent? Is it running? Is the port listening? (netstat -pantu | grep LISTEN)

On June 26, 2017 12:06:02 AM GMT+02:00, newdietpi <notifications@github.com> wrote:
>I get the following error when trying to access through luci.
>
>I have the rpc package installed, the ip set in the config.
>
>`/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute cbi dispatcher
>target for entry '/admin/rtorrent/main'.
>The called action terminated with an exception:
>/usr/lib/lua/rtorrent.lua:48: 
>
>Failed to connect to rtorrent: rpc port not reachable!
>Possible reasons:
>- not the rpc version of rtorrent is installed
>- scgi port is not defined in .rtorrent.rc (scgi_port = 127.0.0.1:5000)
>- rtorrent is not running (ps | grep rtorrent)
>
>stack traceback:
>	[C]: in function 'assert'
>	/usr/lib/lua/luci/dispatcher.lua:460: in function 'dispatch'
>	/usr/lib/lua/luci/dispatcher.lua:141: in function
></usr/lib/lua/luci/dispatcher.lua:140>`
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wolandmaster/luci-app-rtorrent/issues/19

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by newdietpi** [comment]
According to  (netstat -pantu | grep LISTEN) it isn't running.

Not sure why, do you have any ideas? I'll go through the guide step by step again and see if I missed anything

**Comment by ilkarataev** [comment]
Hi i have problem with torrent list.When i add the first torrent file or url the page didn' t downloads the error Bad Gateway.
rtorrent work and download the torrent file but at Luci web interface didn't load.

**Comment by wolandmaster** [comment]
Did you see any suspicious in logread output? Are you using [install destinations](https://wiki.openwrt.org/doc/techref/opkg#installation_destinations) in opkg? I guess it is related to wget dependencies.

**Comment by tplink3020** [comment]
Hi there, having same problem with luci-app-rtorrent.
Here is my System log:
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: /usr/lib/lua/luci/dispatcher.lua:433: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: The called action terminated with an exception:
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: /usr/lib/lua/rtorrent.lua:48: 
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: 
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: Failed to connect to rtorrent: rpc port not reachable!
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: Possible reasons:
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: - not the rpc version of rtorrent is installed
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: - scgi port is not defined in .rtorrent.rc (scgi_port = 127.0.0.1:5000)
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: - rtorrent is not running (ps | grep rtorrent)
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: 
Mon Feb 26 08:30:05 2018 daemon.err uhttpd[940]: stack traceback:

rtorrent is running:
root@OpenWrt:~# ps | grep rotrrent
 1252 root      1356 S    grep rotrrent

but port number for rtorrent is wrong:
root@OpenWrt:~# netstat -pantu | grep LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      940/uhttpd
tcp        0      0 0.0.0.0:6964            0.0.0.0:*               LISTEN      1123/rtorrent
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      1138/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      905/dropbear
tcp        0      0 :::80                   :::*                    LISTEN      940/uhttpd
tcp        0      0 :::53                   :::*                    LISTEN      1138/dnsmasq
tcp        0      0 :::22                   :::*                    LISTEN      905/dropbear


root@OpenWrt:~# cat /root/.rtorrent.rc
encoding_list = UTF-8
system.umask.set = 022
port_range = 23877-23877
port_random = no
check_hash = no
trackers.enable = 1

scgi_port = 127.0.0.1:5000
encryption = allow_incoming, try_outgoing, enable_retry

directory = /mnt/sda2/transmission/complete
session = /mnt/sda2/rtorrent/session/

schedule = rss_downloader,300,300,"execute=/usr/lib/lua/rss_downloader.lua"


root@OpenWrt:~# cat /etc/init.d/rtorrent
#!/bin/sh /etc/rc.common

START=99
STOP=99

SCREEN=/usr/sbin/screen
PROG=/usr/bin/rtorrent

start() {
  sleep 3
  $SCREEN -dm -t rtorrent nice -19 $PROG
}

stop() {
  killall rtorrent
}

**Comment by ilkarataev** [comment]
Check permissions for /mnt/sda2/.
Maybe chmod -R 777 /mnt/sda2 help you.

**Comment by tplink3020** [comment]
@ilkarataev unfortunately changing permissions didn't help
but then I chaged 
local SCGI_ADDRESS = "localhost" to local SCGI_ADDRESS = 127.0.0.1
and a magic is happened :)

**Comment by wolandmaster** [comment]
Regarding the above "ps" output: the rtorrent was not running, only the grep command pid was listed.

When a lot of torrent files are added to rtorrent or lot of connections are handled by rtorrent then the system could slow down. Did you applied the kernel settings that I mentioned on the readme page? Is swap partition/file configured well?
