### ISSUE TITLE
Can't install: luacurl

### ISSUE THREAD

**Issue by netomx** [wolandmaster/luci-app-rtorrent#2]
I download the ipkg manually but it says that luacurl is missing, and I can't find it on the repo

**Comment by netomx** [comment]
I installed it from:

https://downloads.openwrt.org/barrier_breaker/14.07/ramips/rt305x/packages/oldpackages/luacurl_20140207-1_ramips_24kec.ipk

But on chaos, it doesn't work, asks for luci module.

**Comment by wolandmaster** [comment]
This app is not tested on chaos calmer at all. I'll check it and commit a fix.

**Comment by netomx** [comment]
Thanks

**Comment by FireCulex** [comment]
Any luck?

**Comment by wolandmaster** [comment]
The OpenWrt 15.05 (Chaos Calmer) compatible version added to releases. The install instruction (README.md) updated accordingly.
