### ISSUE TITLE
Rtorrent won't listen on LEDE 17

### ISSUE THREAD

**Issue by lastblade** [wolandmaster/luci-app-rtorrent#20]
hello,

idon't know why but i got this error over and over.

**/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
The called action terminated with an exception:
/usr/lib/lua/rtorrent.lua:48:** 

root@LEDE:~ ps | grep rtorrent
 1437 root      1480 S    {screen} /usr/sbin/SCREEN -dm -t rtorrent nice -19 /usr/bin/rtorrent
 1439 root      7592 S N  {rtorrent main} /usr/bin/rtorrent
 1581 root      1184 S    grep rtorrent
root@LEDE:~ netstat -pantu | grep LISTEN
tcp        0      0 127.0.0.1:139           0.0.0.0:*               LISTEN      1184/smbd
tcp        0      0 192.168.1.1:139         0.0.0.0:*               LISTEN      1184/smbd
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      1015/uhttpd
tcp        0      0 0.0.0.0:6933            0.0.0.0:*               LISTEN      1439/rtorrent
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      1510/dnsmasq
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      982/dropbear
tcp        0      0 127.0.0.1:445           0.0.0.0:*               LISTEN      1184/smbd
tcp        0      0 192.168.1.1:445         0.0.0.0:*               LISTEN      1184/smbd
tcp        0      0 ::1:139                 :::*                    LISTEN      1184/smbd
tcp        0      0 fdc4:63cd:9aba::1:139   :::*                    LISTEN      1184/smbd
tcp        0      0 :::80                   :::*                    LISTEN      1015/uhttpd
tcp        0      0 :::53                   :::*                    LISTEN      1510/dnsmasq
tcp        0      0 :::22                   :::*                    LISTEN      982/dropbear
tcp        0      0 ::1:445                 :::*                    LISTEN      1184/smbd
tcp        0      0 fdc4:63cd:9aba::1:445   :::*                    LISTEN      1184/smbd

I'm using a TPLINK WDR 3600 with LEDE Reboot 17.01.4 r3560-79f57e422d / LuCI lede-17.01 branch (git-17.290.79498-d3f0685)

**Comment by lastblade** [comment]
i dont know why but it is not starting at boot. i have to manually start with **/etc/init.d/rtorrent** restart command

**Comment by lastblade** [comment]
Solved with init.d script provided by **Jcfunc** in issue #7

**Comment by wolandmaster** [comment]
README.md updated accordingly
