### ISSUE TITLE
LUCI page not opening in OpenWRT latest trunk

### ISSUE THREAD

**Issue by OlegVekhov** [wolandmaster/luci-app-rtorrent#21]
Hello! OpenWRT latest at 14.04.2018, rtorrent 0.9.6.

> root@trehgorka-ac58u:/usr/lib/lua# netstat -pantu | grep 5000
> tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      3083/rtorrent

but when I try to open webif

> /usr/lib/lua/luci/dispatcher.lua:500: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
> The called action terminated with an exception:
> /usr/lib/lua/rtorrent.lua:48: 
> 
> Failed to connect to rtorrent: rpc port not reachable!
> Possible reasons:
> - not the rpc version of rtorrent is installed
> - scgi port is not defined in .rtorrent.rc (scgi_port = 127.0.0.1:5000)
> - rtorrent is not running (ps | grep rtorrent)
> 
> stack traceback:
> 	[C]: in function 'assert'
> 	/usr/lib/lua/luci/dispatcher.lua:500: in function 'dispatch'
> 	/usr/lib/lua/luci/dispatcher.lua:127: in function </usr/lib/lua/luci/dispatcher.lua:126>

**Comment by myeveryheart** [comment]
same problem.

**Comment by wolandmaster** [comment]
The new version [0.2.0](https://github.com/wolandmaster/luci-app-rtorrent/releases/tag/0.2.0) tested in a docker container and working well with OpenWrt 19.07.7
