### ISSUE TITLE
Form token mismatch adding torrent

### ISSUE THREAD

**Issue by ivan1970** [wolandmaster/luci-app-rtorrent#23]
Hello All,
I installed OpenWRT 18.06.1. rtorrent works fine, but when I try to add a torrent file using luci-app-rtorrent I receive http 403 forbidden error and this message is shown: 
![immagine](https://user-images.githubusercontent.com/5707555/47268445-65b18480-d551-11e8-9ed6-a3d05afadbde.png)

moreover into system log i found this message:

> daemon.err uhttpd[1150]: Model rtorrent/add returns SimpleForm but is dispatched via cbi(),
> daemon.err uhttpd[1150]: please change admin/rtorrent/add to use the form() action instead.
could you help me to understand this issue?
thanks
Ivan

**Comment by ivan1970** [comment]
but there is way to use rtorrent without luci-app?

**Comment by wolandmaster** [comment]
Sure, this tool is only a web client for rtorrent, not contain rtorrent at all.
Just install the rtorrent package (opkg install rtorrent-rpc). You can use the configuration file (.rtorreent.rc) and the start script (init.d/rtorrent) from this project.

**Comment by omegadefender** [comment]
Hi wolandmaster

Could you give us an update on when this issue might be resolved? Its still occurring.

**Comment by ZeroVisionGT** [comment]
Hi, wolandmaster! Did you find a solution to this problem?

**Comment by wolandmaster** [comment]
I not yet upgraded my HW to newer firmware, so I unable to check/solve the problem. Maybe in the winter vacation, I have some time for it.

**Comment by avengermsoft** [comment]
@ZeroVisionGT @omegadefender  @ivan1970 
See https://github.com/avengermsoft/luci-app-rtorrent/commit/203d690525ccace94fd2658ba4508cfa315d6386

**Comment by wolandmaster** [comment]
The new version (0.2.0) fully supports 19.07.
