### ISSUE TITLE
Checkboxes are not working

### ISSUE THREAD

**Issue by lukiluki123** [wolandmaster/luci-app-rtorrent#25]
Checkboxes are not working in List page on Openwrt 21.02

![Clipboard01](https://user-images.githubusercontent.com/36706964/123508040-4a399880-d66d-11eb-86f4-50dbc7feebfa.png)

**Comment by sidhartharoul** [comment]
I got the same issue 

> Checkboxes are not working in List page on Openwrt 21.02
> 
> ![Clipboard01](https://user-images.githubusercontent.com/36706964/123508040-4a399880-d66d-11eb-86f4-50dbc7feebfa.png)

I got the  same issue in 21.02.0-rc3

**Comment by wolandmaster** [comment]
Both of you are using 21.02. Honestly, I have not yet tried that version.
I will try it and make the necessary changes. BTW, which browser are you using?

**Comment by sidhartharoul** [comment]
> Both of you are using 21.02. Honestly, I have not yet tried that version.
> I will try it and make the necessary changes. BTW, which browser are you using?

I tried in both Chrome and edge browser

**Comment by wolandmaster** [comment]
Fixed in [0.2.1](https://github.com/wolandmaster/luci-app-rtorrent/releases/tag/0.2.1)

**Comment by sidhartharoul** [comment]
Thanks @wolandmaster , working for me

**Comment by wolandmaster** [comment]
@sidhartharoul: Thanks for the bug report and the testing!
@lukiluki123: Koszi a hibajegyet, nyugodtan irj, ha barmit talalsz meg.
