### ISSUE TITLE
For Attitude Adjustment

### ISSUE THREAD

**Issue by sindhus** [wolandmaster/luci-app-rtorrent#3]
hi! thanks for writing this. Is this available for Attitude Adjustment release of Openwrt? Thanks

**Comment by wolandmaster** [comment]
Unfortunately not. I made the first version on Barrier Breaker. I try to keep it in one track and support only the latest OpenWrt release, so I suggest you upgrade to Chaos Calmer. (most probably with a small modification it would work on Attitude Adjustment as well, so try it if you like ;-)
