### ISSUE TITLE
Can not open torrent list

### ISSUE THREAD

**Issue by liuyang1204** [wolandmaster/luci-app-rtorrent#5]
I followed installation instruction, but can not open "torrent list" in luci,

```
/usr/lib/lua/luci/dispatcher.lua:433: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
The called action terminated with an exception:
/usr/lib/lua/xmlrpc/scgi.lua:24: attempt to index local 'sock' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:433: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>
```

Don't  know why.

**Comment by kosztik** [comment]
Exactly same error. Can you help me ?
Szia, ugyanaz a hiba mint liuyang1204 -nél. Segíts kérlek:

Firmware Version	OpenWrt Barrier Breaker 14.07 / LuCI Trunk (0.12+svn-r10530) 



/usr/lib/lua/luci/dispatcher.lua:448: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/main'.
The called action terminated with an exception:
/usr/lib/lua/xmlrpc/scgi.lua:24: attempt to index local 'sock' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:448: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:195: in function </usr/lib/lua/luci/dispatcher.lua:194>

**Comment by wolandmaster** [comment]
This error message indicates that the rpc port of rtorrent is not reachable.

Please check the followings:
* rtorrent-rpc properly installed
```
# opkg list-installed | grep rtorrent
luci-app-rtorrent - 0.1.3
rtorrent-rpc - 0.9.4-git-0-7343e33a6a0d279179b304a380bf011f1c8be64a
```
* scgi port 5000 defined in rtorrent config file
```
# grep scgi /root/.rtorrent.rc
scgi_port = 127.0.0.1:5000
```
* rtorrent started
```
# ps | grep rtorrent
 9081 root      5816 S    {screen} SCREEN -dm -t rtorrent nice -19 rtorrent
 9082 root     91112 S N  rtorrent
29077 root      1196 S    grep rtorrent
```
* scgi (rpc) port is open
```
# netstat -pantu | grep 5000
tcp        0      0 127.0.0.1:5000      0.0.0.0:*       LISTEN      9082/rtorrent
```

**Comment by wolandmaster** [comment]
irtam valaszt:

https://github.com/wolandmaster/luci-app-rtorrent/issues/5

**Comment by kosztik** [comment]
Perfect! Thank you very much for your fast answer!
Nagyon szépen köszönöm! Kedves vagy!

**Comment by liuyang1204** [comment]
Hey, I figured out the reason was "rtorrent failed to start", it reports the `session` dir is not created. 
I manually created the dir, then it is ok.

BTW, download speed is really good, but it still uses a lot of memory

```
88844K
```

And my router only has 120M memory.
I switched from transmission just because its huge memory usage.

Do you have some suggestion about the memory usage?

**Comment by wolandmaster** [comment]
My router has only 64M RAM, so the memory issues are more serious for me. The router is often reboots when too much torrent peers are connected, so I limited the maximum number of clients in .rtorrent.rc:

```
# Maximum and minimum number of peers to connect to per torrent.
min_peers = 10
max_peers = 30

# Same as above but for seeding completed torrents (-1 = same as downloading)
min_peers_seed = 10
max_peers_seed = 20

# Maximum number of simultanious uploads per torrent.
max_uploads = 10

# Parallel downloads count
max_downloads_global = 4
```
Besides that, somehow the current version of openwrt/rtorrent is more unstable that the previous one. I hope the issues will fixed in the next release.

**Comment by munjeni** [comment]
I had allso problem starting torrent from luci web interface, rtorrent start and listen to the port but not on the port 5000, probably problem is because screen didn;t start as a root user. Solved problem by installing sudo (opkg install sudo), and adding sudo to the init.d rtorrent:

#!/bin/sh /etc/rc.common

START=99
STOP=99

SCREEN=`which screen`
PROG=`which rtorrent`
SUDO=`which sudo`

start() {
	sleep 3
	if [ -e /mnt/rtorrent ]; then
		$SUDO -u root $SCREEN -dms -t rtorrent $PROG
	fi
}

stop() {
	killall -9 rtorrent
	killall -9 wget
}

**Comment by munjeni** [comment]
Now I see another problem and unable to solve. hen I add .torrent file which contain huge file list e.g. an music torrent which contain e.g. 1000 files, than I'm unable to open luci torrent list link, getting:

Bad Gateway
The process did not produce any response

Do you have idea what might be a isue? On command line I can see a list of files.
