### ISSUE TITLE
luci broken after installation of app-luci-rtorrent

### ISSUE THREAD

**Issue by remlei** [wolandmaster/luci-app-rtorrent#6]
after reboot, the luci web stops working, it only pops-up a weird luci download pop-up, removing the app-luci-rtorrent did fix this

using Openwrt_x86 Generic

**Comment by wolandmaster** [comment]
Could you please send me the text of the pop-up that you mentioned and the result of ```logread``` command.

**Comment by wolandmaster** [comment]
Probably the problem is not related to app-luci-rtorrent, especially if it isn't fixed when you removed the package.
