### ISSUE TITLE
error in Openwrt Designated Driver

### ISSUE THREAD

**Issue by gendouhydeist** [wolandmaster/luci-app-rtorrent#9]
Whenever I open Torrent List or Add Torrent I get this error.

/usr/lib/lua/luci/dispatcher.lua:456: Failed to execute cbi dispatcher target for entry '/admin/rtorrent/add'.
The called action terminated with an exception:
/usr/lib/lua/xmlrpc/scgi.lua:24: attempt to index local 'sock' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:456: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

EDIT:
When I disabled the init then reboot, then manually running rtorrent it works, but not with screen.

**Comment by wolandmaster** [comment]
This error message indicates that rtorrent is not running properly. Please check issue #5 and #7. This app is only a client therefore not responsible for starting/configuring rtorrent itself.
